### ISSUE TITLE
On OSX had to switch from 'nodejs' to 'node'.

### ISSUE THREAD

**Issue by pydanny** [rbann/pygments-lexer-babylon#1]
Any chance we can specify the `nodejs` command? I guess I could symlink it if necessary.

**Comment by ghost** [comment]
An env var maybe?

**Comment by ghost** [comment]
Added an env var to control the command: PYGMENTS_NODE_COMMAND

**Comment by benwiley4000** [comment]
First: Thanks so much for creating this it was exactly what I needed!
Second: I want to second that this could be useful. Of course, I'm on Ubuntu and had no problem, but "nodejs" as the path variable is unique to Ubuntu I think. There are issues posted all over the internet by folks who didn't realize they need to create a symlink between "nodejs" and "node" in order for code to run on Ubuntu. So accepting "node" by default would be good, since it seems like that's more the "official" bin name.
